### PR TITLE
Add option for lowerCase when normalizing

### PR DESCRIPTION
**Pull request by Sprokof**
Hi, i improved email normalization by adding lower case option, it's related to 171 issue

### CODE REVIEW

**Comment by RohanNagar** [comment]
Hi @Sprokof, thank you so much for the contribution!

This looks great overall to me. I am wondering if we can default the option to `false` for now? That way the feature can be released without causing any breaking changes. I would then change the default to `true` when v2.0 is ready.

**Comment by Sprokof** [comment]
Yes, we can set param to false by default

**Comment by Sprokof** [comment]
Can you explain why snyk bring this error? I must configure something?

**Comment by RohanNagar** [comment]
Thanks for updating the default! I don't know what is going on with the snyk check, but don't worry about it. Your code looks great to me. I'm going to go ahead and merge this.

Thanks again for the contribution, it is really appreciated!

**Pull request merged**
